name: Build and Deploy Temperature API

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Temperature.APi/Temperature.APi.csproj

    - name: Build the project
      run: dotnet build Temperature.APi/Temperature.APi.csproj --configuration Release --no-restore

    - name: Publish the app
      run: dotnet publish Temperature.APi/Temperature.APi.csproj --configuration Release --output publish

    - name: Upload published files to server via manual SCP
      run: |
        mkdir -p ~/.ssh
        echo "${{ env.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 4.231.98.81 >> ~/.ssh/known_hosts
        scp -r publish/* gitdeploy@4.231.98.81:"C:/CSIPRODUCTION/Temp"
      env:
        SSH_PRIVATE_KEY: |
          -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAt/8rr0++XBuLFZk9CR/mMZpQkaJpNfrTb3fMnO012ANThjPdQuYn
+Ypf+D23IwFSnHogX2RIkYnCReKKHB9UFe1Z4+mS0pQBD6hBTqLeZGlRo8zX/cs9fBzdg4
wPO/xn61ndaCFAePFnDvMjH2wcVpiYP9yiSi0hQYlq+YFbPR17gpMYV1t6obXwpnfW9fSd
KOGnV31n4P89UryFiwxVwQ+Mv2WUCqbc8VvTIWLVIbuTL4sRMPdRHnpc6TF9TDJJ3KOhv6
msuaU9wzcHa04W8yrRtiDKdCqejE4rpeeKad0sGOP2RE9XfhvsHOK1m624ufHUPWcAlJ3S
fVn+fpcJhmCmm+goe4/NfgZAG9hyRK6DJ//PQtICo2FHpaJYLJqUVckR0tWH7CC8kN7+3t
H7dAZ8MB+3ZXtum/0pG/mHJQdjsl2gjuK43H05k9qLf69if/LFj7QYe9z3TJ/ZUKdBRtps
KF1OLgE740EQhYt/bHaUeTQv4rnG11W+vIL/TJKa51cQy8bmuLsYTa+pgves9I8QPP0aPQ
yvCBTt25B5R8gK6/Ib1K+TPAzZi0n7MlzYq2bXaGINGHPQMxdg/dKLW5NaDhHk+ZvdEnr2
/X6Vtr6qpQ8rfRntg3OwJ6i+ienMZhajOhwYgk8593l4vpniDt3Xa6fQZABnQAZ/E/toAL
kAAAdQNoI9eTaCPXkAAAAHc3NoLXJzYQAAAgEAt/8rr0++XBuLFZk9CR/mMZpQkaJpNfrT
b3fMnO012ANThjPdQuYn+Ypf+D23IwFSnHogX2RIkYnCReKKHB9UFe1Z4+mS0pQBD6hBTq
LeZGlRo8zX/cs9fBzdg4wPO/xn61ndaCFAePFnDvMjH2wcVpiYP9yiSi0hQYlq+YFbPR17
gpMYV1t6obXwpnfW9fSdKOGnV31n4P89UryFiwxVwQ+Mv2WUCqbc8VvTIWLVIbuTL4sRMP
dRHnpc6TF9TDJJ3KOhv6msuaU9wzcHa04W8yrRtiDKdCqejE4rpeeKad0sGOP2RE9Xfhvs
HOK1m624ufHUPWcAlJ3SfVn+fpcJhmCmm+goe4/NfgZAG9hyRK6DJ//PQtICo2FHpaJYLJ
qUVckR0tWH7CC8kN7+3tH7dAZ8MB+3ZXtum/0pG/mHJQdjsl2gjuK43H05k9qLf69if/LF
j7QYe9z3TJ/ZUKdBRtpsKF1OLgE740EQhYt/bHaUeTQv4rnG11W+vIL/TJKa51cQy8bmuL
sYTa+pgves9I8QPP0aPQyvCBTt25B5R8gK6/Ib1K+TPAzZi0n7MlzYq2bXaGINGHPQMxdg
/dKLW5NaDhHk+ZvdEnr2/X6Vtr6qpQ8rfRntg3OwJ6i+ienMZhajOhwYgk8593l4vpniDt
3Xa6fQZABnQAZ/E/toALkAAAADAQABAAACAApuEYjfiVfpS8oOpLIWt9LJ/5Ux0qr3q/Ke
pN+kZq/3CE4MNJetOkjf+i61OONoGMm79ofRxHdTisqxW8jaUcbobHcJ74O2VhUQIZuWie
rBOZqCax/83GBjtn7VequY1D84Gd/kOqZgcModKDmIxFZ4UfEUzbJMupzfcEvydDyTpkOx
mOiiy+HM0XZuRqYslpgRqo3AExpi/ZPqEdve+CF4gy76UBkGenHIFcDHvHMsEdzZEkFnU5
bZstiZMJQYKa2zLOETejIP1t9xCB+iDpT8MWUUmMVbAR/M8pZ1+JelrPFAQt5+bOQ+KvU8
OLU5dMY9mh1c8GB8TclDR7TfVO/LZzc/9+hyGgWVbzKKzfLXeoxgQXtSFigCj8/HRNvYZ1
dYkCwka2u1HamGYRyAhodFhjtSZ2+vMHzP/TCTJ2QB4i03JKdyD3AkZAzclOleulTgXQx8
2rQiaVrIvEtsdxEHqh4kLQ+/JaOAChzwGrKv9qaHwDFua8pq9t2/OQLlmldV7b1Msh+63H
8h86ipZaRwVuoBe39tgC+g0YuUv5uOhoJjIFjsQ7PwzcWFHhwsddXLnspSxHEqNbjAOAtu
Debi6bQuLtTuAk0JaSB1M3vVAue9/+Qh3ttvXEgJiSls70c7QM+iknkOtUTfsO7tdc2Ufp
S5NmK9zfzXGb8XhJjxAAABAEgcbOLbT6HEti/J7IuASXNlAcSPAfA0vkPL55Fot/u2fFok
2RwjGrEpSJuusIZI76EnNJTfGwlxURemAfUaxBzPj1Q/5V0+IAB/yQmq1hA6H0AAj5lfMu
kdo0OLT23iXZmknpA/ZAq2S2gf4FqarkpJySvkOlGVxMY/tLtgwUFtdjHaivCLcC56HjHm
LBHImP3b+8j5GK8WRLxhfs/G+4Gbu3/Abkwngje7XDmFHysRV9aE8fkiCZPDdN69Q+Rqlp
QDrnVj4jzQkSVfjGpYmzPex0aBwCWVnng4DEJ6kH+QtXssVSq40kYpQGSltcykpTDiJ3t/
HODsUHqGeCf82B4AAAEBAO3ilHSxaTDk80euhA5MiYgTTZlivITeEFZLQKv92eWMwBTBOm
KzRyxyf6/4+tcMdAstSZBhTilVwYGKJLiLqSKCT/j9gSFpJBwiw+u5mm6x7bVZ75wDjx/o
rAO/RHwo6F9KPOME/JeJYL94U744zjLV9YKprGmZvSOP3klaR09IVcfLdzyGnzk3uUF/tV
XZpBc8fg6n3uWAosiEEGHVWjunhz9BRoMnHaiuPMRkGwRmaw+P4Ca/FHhSptpDcfuEJsQw
Cp2FXzoATao9Q3F4nR0S5YhOayPC2yNyhOj16iq3/IDIHfoiXriq7WOylzkuH22tpCbm+8
HO4BUvysYqdM0AAAEBAMYCEmUe+fnatniApImu0Sv94uO2N+llwaU36LZcUEb3wLXu1S+s
dg8AOHWcmsEMGAcOnkxxB1wCHPKyba+nZyIg6ZJ4kJDOkbuN8J8bW1HwEID1CrRJgPSiN/
+aI9Iq8MuKQz+hMjm1opJMHqFEfxJhqKud+Td9vOi0pFW1IyCk/S2e1BAIAOhUn9alHAwz
hhTHhmXm1OKBN2d7nSFT5w/LdAWQVgnsnxR12Ee8E2DaSZzE4g04Ye4y2i4JyxekiBCoHK
7yKp8beT26xPw8G3Up/eWSJ/XSo3mJjAWBt+1WsTcIddOsJ8d2VF9iDdqfd2Bwz3FC/j+C
fGVzhO8/250AAAAUZ2l0ZGVwbG95QHlvdXJzZXJ2ZXIBAgMEBQYH
-----END OPENSSH PRIVATE KEY-----

